# Generated by Django 3.2.15 on 2023-02-20 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Широта')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
