# Generated by Django 3.2.15 on 2023-02-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='update_time',
            new_name='update_at',
        ),
    ]
