version: "3"


services:
  db:
    restart: always
    image: "postgres:13-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    container_name: star_burger_web
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./media:/code/media
      - /code/staticfiles
      - .:/code
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: star_burger_frontend
    build: ./frontend
    volumes:
      - ./frontend/bundles-src/:/code/frontend/bundles-src/
      - ./static/:/code/frontend/bundles/

  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
