# Generated by Django 3.2.15 on 2023-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Необработанный'), ('B', 'Передан в ресторан'), ('C', 'Передан курьеру'), ('D', 'Выполнен')], default='A', max_length=1),
        ),
    ]
