# Generated by Django 3.2.15 on 2023-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Необработан'), ('B', 'Передан в ресторан'), ('C', 'Передан курьеру'), ('D', 'Выполнен')], db_index=True, default='A', max_length=1, verbose_name='Статус'),
        ),
    ]
