# Generated by Django 3.2.15 on 2023-02-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_alter_order_called_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registrated_at',
            new_name='creation_at',
        ),
    ]
