# Generated by Django 3.2.15 on 2023-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_auto_20230218_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронно')], db_index=True, default='C', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
