# Generated by Django 3.2.15 on 2023-02-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0016_auto_20230223_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Необработан'), ('B', 'Передан в ресторан'), ('C', 'Передан курьеру'), ('D', 'Выполнен')], db_index=True, default='E', max_length=1, verbose_name='Статус'),
        ),
    ]
