# Generated by Django 3.2.15 on 2023-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронно')], db_index=True, default='E', max_length=1, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Необработан'), ('B', 'Передан в ресторан'), ('C', 'Передан курьеру'), ('D', 'Выполнен')], db_index=True, default='A', max_length=1, verbose_name='Статус'),
        ),
    ]
