# Generated by Django 3.2.15 on 2023-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0018_auto_20230223_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронно')], db_index=True, max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
