# Generated by Django 3.2.15 on 2023-02-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0021_rename_order_restaurant_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Выбранный для приготовления ресторан'),
        ),
    ]
