# Generated by Django 3.2.15 on 2023-03-11 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0022_alter_order_cooking_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
