# Generated by Django 3.2.15 on 2023-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesapp', '0002_rename_update_time_place_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Адрес'),
        ),
    ]
