# Generated by Django 3.2.15 on 2023-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesapp', '0003_alter_place_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=255, unique=True, verbose_name='Адрес'),
        ),
    ]
