# Generated by Django 3.2.15 on 2023-02-23 15:27

from django.db import migrations


def copy_price_field_to_total_price_field(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    for order_product in OrderProduct.objects.all():
        order_product.total_price = order_product.price
        order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0013_orderproduct_total_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_field_to_total_price_field)
    ]
